FROM node:20-bookworm

WORKDIR /app/frontend

COPY frontend/package.json frontend/package-lock.json ./

RUN npm ci

WORKDIR /app

RUN ln -s /app/frontend/node_modules /app/node_modules

COPY tsconfig.json tsconfig.base.json ./

COPY backend ./backend
COPY frontend ./frontend

WORKDIR /app/frontend

ENV NODE_ENV=production

RUN npm run build

EXPOSE 4321

CMD ["node", "./dist/server/entry.mjs"]
